/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import com.mysql.cj.protocol.Resultset;
import com.mysql.cj.xdevapi.Statement;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author IRSYAD KAMAL
 */
public class Project1 extends javax.swing.JFrame {
    private DefaultTableModel DftTblModel_barang;
    private String SQL; 
    /**
     * Creates new form Project1
     */
    public Project1() {
        initComponents();
        TampilData();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        
        
    }
    
    public void Clean(){
        txt_kode.setText("");
        txt_nama.setText("");
        txt_jml.setText("");
        box_jenis.setSelectedIndex(0);

        txt_note.setText(""); 
    }
    
    private void cariData(String key){


DftTblModel_barang = new DefaultTableModel();
        DftTblModel_barang.addColumn("Tanggal");
        DftTblModel_barang.addColumn("Kode Barang");
        DftTblModel_barang.addColumn("Nama Barang");
        DftTblModel_barang.addColumn("Jumlah Barang");
        DftTblModel_barang.addColumn("Jenis Barang");
        DftTblModel_barang.addColumn("Keluar/Masuk");
        DftTblModel_barang.addColumn("Note");
        tbdata.setModel(DftTblModel_barang);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM tb_sipro1 WHERE kode LIKE '%"+key+"%' OR nama LIKE '%"+key+"%' OR jenis LIKE '%"+key+"%'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_barang.addRow(new Object[]{
                    res.getString("tanggal"),
                    res.getString("kode"),
                    res.getString("nama"),
                    res.getString("jumlah"),
                    res.getString("jenis"),
                    res.getString("in_out"),
                    res.getString("note")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    
    public final void TampilData() {
        DftTblModel_barang = new DefaultTableModel();
        DftTblModel_barang.addColumn("Tanggal");
        DftTblModel_barang.addColumn("Kode Barang");
        DftTblModel_barang.addColumn("Nama Barang");
        DftTblModel_barang.addColumn("Jumlah Barang");
        DftTblModel_barang.addColumn("Jenis Barang");
        DftTblModel_barang.addColumn("Keluar/Masuk");
        DftTblModel_barang.addColumn("Note");
        tbdata.setModel(DftTblModel_barang);
        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT * FROM tb_sipro1";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_barang.addRow(new Object[]{
                    res.getString("tanggal"),
                    res.getString("kode"),
                    res.getString("nama"),
                    res.getString("jumlah"),
                    res.getString("jenis"),
                    res.getString("in_out"),
                    res.getString("note")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb = new javax.swing.ButtonGroup();
        bg_awal = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        btn_panAbout = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_panForm = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_panALL = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JPanel();
        tx_exit = new javax.swing.JLabel();
        ic_exit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        panel_border = new keeptoo.KGradientPanel();
        label_user = new javax.swing.JLabel();
        lbl_border = new javax.swing.JLabel();
        panel_utama = new javax.swing.JPanel();
        panel_show = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        box_jenis = new javax.swing.JComboBox<>();
        btn_submit = new javax.swing.JPanel();
        tx_simpan = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_kode = new javax.swing.JTextField();
        txt_jml = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        rb_in = new javax.swing.JRadioButton();
        rb_out = new javax.swing.JRadioButton();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_note = new javax.swing.JTextArea();
        btn_submit2 = new javax.swing.JPanel();
        tx_perbarui = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_about = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panel_input = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdata = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        tx_cari = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        btn_dlt = new javax.swing.JPanel();
        tx_hapus = new javax.swing.JLabel();
        btn_view = new javax.swing.JPanel();
        tx_lihat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg_awal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(137, 72, 234));
        kGradientPanel1.setkGradientFocus(-450);
        kGradientPanel1.setkStartColor(new java.awt.Color(54, 30, 90));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_panAbout.setBackground(new java.awt.Color(64, 43, 100));
        btn_panAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_panAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_panAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_panAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_panAboutMouseExited(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icons8_about_16px.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("About Aplication");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout btn_panAboutLayout = new javax.swing.GroupLayout(btn_panAbout);
        btn_panAbout.setLayout(btn_panAboutLayout);
        btn_panAboutLayout.setHorizontalGroup(
            btn_panAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_panAboutLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btn_panAboutLayout.setVerticalGroup(
            btn_panAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_panAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        kGradientPanel1.add(btn_panAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 260, 50));

        btn_panForm.setBackground(new java.awt.Color(64, 43, 100));
        btn_panForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_panForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_panFormMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_panFormMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_panFormMouseExited(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icons8_add_25px.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Transaksi");
        jLabel5.setToolTipText("");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btn_panFormLayout = new javax.swing.GroupLayout(btn_panForm);
        btn_panForm.setLayout(btn_panFormLayout);
        btn_panFormLayout.setHorizontalGroup(
            btn_panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_panFormLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btn_panFormLayout.setVerticalGroup(
            btn_panFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_panFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        kGradientPanel1.add(btn_panForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 260, 50));

        btn_panALL.setBackground(new java.awt.Color(64, 43, 100));
        btn_panALL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_panALL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_panALLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_panALLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_panALLMouseExited(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icons8_account_16px.png"))); // NOI18N
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Data Barang");
        jLabel7.setToolTipText("");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout btn_panALLLayout = new javax.swing.GroupLayout(btn_panALL);
        btn_panALL.setLayout(btn_panALLLayout);
        btn_panALLLayout.setHorizontalGroup(
            btn_panALLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_panALLLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btn_panALLLayout.setVerticalGroup(
            btn_panALLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_panALLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        kGradientPanel1.add(btn_panALL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 50));

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
        });

        tx_exit.setBackground(new java.awt.Color(255, 255, 255));
        tx_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tx_exit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tx_exit.setText("EXIT");

        ic_exit.setBackground(new java.awt.Color(255, 255, 255));
        ic_exit.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        ic_exit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ic_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icons8_outdent_24px_1.png"))); // NOI18N

        javax.swing.GroupLayout btn_exitLayout = new javax.swing.GroupLayout(btn_exit);
        btn_exit.setLayout(btn_exitLayout);
        btn_exitLayout.setHorizontalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_exitLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(ic_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_exit)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        btn_exitLayout.setVerticalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_exitLayout.createSequentialGroup()
                .addGroup(btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ic_exit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(tx_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 260, 30));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));
        jSeparator1.setRequestFocusEnabled(false);
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, 30));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SIPRO");
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 40));

        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 20));
        jSeparator2.setRequestFocusEnabled(false);
        kGradientPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, 20));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("News701 BT", 1, 8)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(196, 193, 193));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("© sipro_dev 2022");
        jLabel13.setToolTipText("");
        kGradientPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 190, 30));

        bg_awal.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 560));

        panel_border.setkEndColor(new java.awt.Color(126, 79, 196));
        panel_border.setkGradientFocus(700);
        panel_border.setkStartColor(new java.awt.Color(54, 30, 90));
        panel_border.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_user.setForeground(new java.awt.Color(204, 204, 204));
        label_user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_user.setText("Hello, wellcome  ");
        panel_border.add(label_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 247, 30));

        lbl_border.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_border.setForeground(new java.awt.Color(204, 197, 204));
        lbl_border.setText("Transaksi ...");
        lbl_border.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lbl_borderComponentShown(evt);
            }
        });
        panel_border.add(lbl_border, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 440, 45));

        bg_awal.add(panel_border, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 830, 130));

        panel_utama.setLayout(new java.awt.CardLayout());

        panel_show.setBackground(new java.awt.Color(242, 242, 242));

        jPanel1.setBackground(new java.awt.Color(103, 57, 172));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Kode Barang");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Nama Barang");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Barang In/Out");

        box_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Disini >", "Beras", "Tepung", "Sagu", "Gula Pasir", "Minyak Goreng", "Bumbu Dapur", "Telur", "Minuman", "Daging" }));
        box_jenis.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btn_submit.setBackground(new java.awt.Color(255, 255, 255));
        btn_submit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.magenta, java.awt.Color.blue, java.awt.Color.magenta, java.awt.Color.blue));
        btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_submitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_submitMouseExited(evt);
            }
        });

        tx_simpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tx_simpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx_simpan.setText("Simpan");
        tx_simpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btn_submitLayout = new javax.swing.GroupLayout(btn_submit);
        btn_submit.setLayout(btn_submitLayout);
        btn_submitLayout.setHorizontalGroup(
            btn_submitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_submitLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(tx_simpan)
                .addGap(38, 38, 38))
        );
        btn_submitLayout.setVerticalGroup(
            btn_submitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tx_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        txt_nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        txt_kode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kodeActionPerformed(evt);
            }
        });

        txt_jml.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_jml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jmlActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("Jumlah Barang");

        jLabel42.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jLabel42.setText("Jenis Barang :");

        rb_in.setBackground(new java.awt.Color(255, 255, 255));
        jb.add(rb_in);
        rb_in.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rb_in.setText("Masuk");
        rb_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_inActionPerformed(evt);
            }
        });

        rb_out.setBackground(new java.awt.Color(255, 255, 255));
        jb.add(rb_out);
        rb_out.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rb_out.setText("Keluar");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Catatan :");

        txt_note.setColumns(20);
        txt_note.setRows(5);
        jScrollPane3.setViewportView(txt_note);

        btn_submit2.setBackground(new java.awt.Color(255, 255, 255));
        btn_submit2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.magenta, java.awt.Color.blue, java.awt.Color.magenta, java.awt.Color.blue));
        btn_submit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_submit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_submit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_submit2MouseExited(evt);
            }
        });

        tx_perbarui.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tx_perbarui.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx_perbarui.setText("Perbarui");
        tx_perbarui.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btn_submit2Layout = new javax.swing.GroupLayout(btn_submit2);
        btn_submit2.setLayout(btn_submit2Layout);
        btn_submit2Layout.setHorizontalGroup(
            btn_submit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_submit2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(tx_perbarui, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        btn_submit2Layout.setVerticalGroup(
            btn_submit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tx_perbarui, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(rb_in, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rb_out, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(box_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btn_submit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_in)
                    .addComponent(rb_out))
                .addGap(18, 18, 18)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_submit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        jScrollPane1.setViewportView(jPanel7);

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/2842680-removebg-preview (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout panel_showLayout = new javax.swing.GroupLayout(panel_show);
        panel_show.setLayout(panel_showLayout);
        panel_showLayout.setHorizontalGroup(
            panel_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_showLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        panel_showLayout.setVerticalGroup(
            panel_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_showLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(panel_showLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_utama.add(panel_show, "card3");

        panel_about.setBackground(new java.awt.Color(242, 242, 242));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("ABOUT APLICATION");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icons8_id_male_student_100px.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("selain itu aplikasi ini berbasis desktop dengan tujuan memberikan penampilan GUI keren "); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Aplikasi ini dikembangkan dan dapat dijalankan di operasi Windows,"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("serta memberikan kemudahan user untuk mengakses aplikasi ini. "); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Aplikasi My SIPRO"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Version 1.0.1 V"); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Develop By SIPRO TEAM"); // NOI18N

        javax.swing.GroupLayout panel_aboutLayout = new javax.swing.GroupLayout(panel_about);
        panel_about.setLayout(panel_aboutLayout);
        panel_aboutLayout.setHorizontalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_aboutLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_aboutLayout.createSequentialGroup()
                        .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(482, Short.MAX_VALUE))
                    .addGroup(panel_aboutLayout.createSequentialGroup()
                        .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(108, 108, 108))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_aboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        panel_aboutLayout.setVerticalGroup(
            panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aboutLayout.createSequentialGroup()
                .addGroup(panel_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_aboutLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_aboutLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(23, 23, 23)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        panel_utama.add(panel_about, "card4");

        panel_input.setBackground(new java.awt.Color(242, 242, 242));

        jScrollPane2.setBorder(null);

        tbdata.setAutoCreateRowSorter(true);
        tbdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tbdata.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Kode Barang", "Nama Barang", "Jumlah Barang", "Jenis Barang", "Masuk/Keluar", "note"
            }
        ));
        tbdata.setGridColor(new java.awt.Color(255, 255, 255));
        tbdata.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tbdata.setRowHeight(25);
        tbdata.setSelectionBackground(new java.awt.Color(122, 71, 221));
        tbdata.setShowGrid(true);
        tbdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdataMouseClicked(evt);
            }
        });
        tbdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbdataKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbdata);
        if (tbdata.getColumnModel().getColumnCount() > 0) {
            tbdata.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbdata.getColumnModel().getColumn(1).setPreferredWidth(10);
            tbdata.getColumnModel().getColumn(2).setPreferredWidth(10);
            tbdata.getColumnModel().getColumn(3).setPreferredWidth(10);
            tbdata.getColumnModel().getColumn(6).setMinWidth(0);
            tbdata.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tx_cari.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tx_cari.setToolTipText("");
        tx_cari.setActionCommand("<Not Set>");
        tx_cari.setBorder(null);
        tx_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_cariActionPerformed(evt);
            }
        });
        tx_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx_cariKeyReleased(evt);
            }
        });
        jPanel3.add(tx_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 0, 320, 20));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 310, 10));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Pencarian");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        btn_dlt.setBackground(new java.awt.Color(255, 255, 255));
        btn_dlt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.magenta, java.awt.Color.blue, java.awt.Color.magenta, java.awt.Color.blue));
        btn_dlt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dltMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dltMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dltMouseExited(evt);
            }
        });

        tx_hapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tx_hapus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx_hapus.setText("Hapus");
        tx_hapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btn_dltLayout = new javax.swing.GroupLayout(btn_dlt);
        btn_dlt.setLayout(btn_dltLayout);
        btn_dltLayout.setHorizontalGroup(
            btn_dltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dltLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(tx_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_dltLayout.setVerticalGroup(
            btn_dltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tx_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        btn_view.setBackground(new java.awt.Color(255, 255, 255));
        btn_view.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.magenta, java.awt.Color.blue, java.awt.Color.magenta, java.awt.Color.blue));
        btn_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_viewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_viewMouseExited(evt);
            }
        });

        tx_lihat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tx_lihat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx_lihat.setText("Lihat");
        tx_lihat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btn_viewLayout = new javax.swing.GroupLayout(btn_view);
        btn_view.setLayout(btn_viewLayout);
        btn_viewLayout.setHorizontalGroup(
            btn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_viewLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(tx_lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btn_viewLayout.setVerticalGroup(
            btn_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tx_lihat, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_inputLayout = new javax.swing.GroupLayout(panel_input);
        panel_input.setLayout(panel_inputLayout);
        panel_inputLayout.setHorizontalGroup(
            panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_inputLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panel_inputLayout.createSequentialGroup()
                            .addComponent(btn_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_dlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        panel_inputLayout.setVerticalGroup(
            panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inputLayout.createSequentialGroup()
                .addGroup(panel_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_inputLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_inputLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btn_dlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        panel_utama.add(panel_input, "card4");

        bg_awal.add(panel_utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 830, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_awal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg_awal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg_awal.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(1086, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_panFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panFormMouseClicked
        // TODO add your handling code here
        panel_utama.removeAll();
        panel_utama.repaint();
        panel_utama.revalidate();
        
        panel_utama.add(panel_show);
        panel_utama.repaint();
        panel_utama.revalidate();
        
        String nam = "Transaksi .....";
        lbl_border.setText(nam);
        Clean();
    }//GEN-LAST:event_btn_panFormMouseClicked

    private void btn_panALLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panALLMouseEntered
        // TODO add your handling code here:
        btn_panALL.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_btn_panALLMouseEntered

    private void btn_panALLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panALLMouseExited
        // TODO add your handling code here:
        btn_panALL.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_btn_panALLMouseExited

    private void btn_panAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panAboutMouseEntered
        // TODO add your handling code here:
        btn_panAbout.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_btn_panAboutMouseEntered

    private void btn_panAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panAboutMouseExited
        // TODO add your handling code here:
        btn_panAbout.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_btn_panAboutMouseExited

    private void btn_panALLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panALLMouseClicked
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.repaint();
        panel_utama.revalidate();
        
        panel_utama.add(panel_input);
        panel_utama.repaint();
        panel_utama.revalidate();
        
        String nam = "Data Barang .....";
        lbl_border.setText(nam);
        Clean();
        
    }//GEN-LAST:event_btn_panALLMouseClicked

    private void btn_panAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panAboutMouseClicked
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.repaint();
        panel_utama.revalidate();
        
        panel_utama.add(panel_about);
        panel_utama.repaint();
        panel_utama.revalidate();
        
        String nam = "About Aplication .....";
        lbl_border.setText(nam);
        
    }//GEN-LAST:event_btn_panAboutMouseClicked

    private void btn_panFormMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panFormMouseEntered
        // TODO add your handling code here:
        btn_panForm.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_btn_panFormMouseEntered

    private void btn_panFormMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_panFormMouseExited
        // TODO add your handling code here:
        btn_panForm.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_btn_panFormMouseExited

    private void lbl_borderComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lbl_borderComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_borderComponentShown

    private void tx_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_cariActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void btn_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseClicked
        // TODO add your handling code here:
        String in_out;
        if (rb_in.isSelected()){
            in_out = "Masuk";
        }else{
            in_out = "Keluar";
        }
        try{
                String sql = "INSERT INTO tb_sipro1(kode, nama, jumlah, jenis, in_out, note) VALUES (" + "'" + txt_kode.getText() + "','" + txt_nama.getText() + "','" 
                + txt_jml.getText() + "','" + box_jenis.getSelectedItem() + "','" + in_out + "','" + txt_note.getText() + "')";
                java.sql.Connection conn=(java.sql.Connection)project.Koneksi.getConnection();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data anda berhasil disimpan");
                TampilData();
                Clean();  
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Gagal disimpan");
                System.out.println(e.getMessage());
            }
    }//GEN-LAST:event_btn_submitMouseClicked

    private void txt_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kodeActionPerformed

    private void txt_jmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jmlActionPerformed

    private void rb_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_inActionPerformed

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_submit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submit2MouseClicked
        // TODO add your handling code here:
        String in_out;
        if (rb_in.isSelected()){
            in_out = "Masuk";
        }else{
            in_out = "Keluar";
        }
        try{
            String sql = "UPDATE tb_sipro1 SET kode='" + txt_kode.getText() + "', nama= '" + txt_nama.getText() + "', jumlah= '" + txt_jml.getText() + "', "
                    + "jenis= '" + box_jenis.getSelectedItem()+"', in_out= '" + in_out + "', note= '" + txt_note.getText() + "' where kode='" + txt_kode.getText() + "'" ; 
            java.sql.Connection conn=(java.sql.Connection)project.Koneksi.getConnection();
                    java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Berhasil disimpan");
                    TampilData();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btn_submit2MouseClicked

    private void btn_dltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dltMouseClicked
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete record ini???", "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
       if (ok==0){
        try{
            String sql="DELETE FROM tb_sipro1 WHERE kode='"+txt_kode.getText()+"'";
            java.sql.Connection conn=(java.sql.Connection)project.Koneksi.getConnection();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.executeUpdate();
            TampilData();
            JOptionPane.showMessageDialog(null, "Delete Data Sukses");
         }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Delete Data Gagal");
        }
       }
    }//GEN-LAST:event_btn_dltMouseClicked

    private void btn_viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewMouseClicked
       
            // TODO add your handling code here:
            panel_utama.removeAll();
            panel_utama.repaint();
            panel_utama.revalidate();
            
            panel_utama.add(panel_show);
            panel_utama.repaint();
            panel_utama.revalidate();
            
            String nam = "Transaksi .....";
            lbl_border.setText(nam);
    }//GEN-LAST:event_btn_viewMouseClicked

    private void tbdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdataMouseClicked
        // TODO add your handling code here:
        int baris = tbdata.rowAtPoint(evt.getPoint());
            String kode = tbdata.getValueAt(baris, 1).toString();
            txt_kode.setText(kode);
            String nama = tbdata.getValueAt(baris, 2).toString();
            txt_nama.setText(nama);
            String jumlah = tbdata.getValueAt(baris, 3).toString();
            txt_jml.setText(jumlah);
            String jenis = tbdata.getValueAt(baris, 4).toString();
            box_jenis.setSelectedItem(jenis);
            
            String note = tbdata.getValueAt(baris, 6).toString();
            txt_note.setText(note);
            
    }//GEN-LAST:event_tbdataMouseClicked

    private void btn_submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseEntered
        // TODO add your handling code here:
        btn_submit.setBackground(new Color(126,79,196));
        tx_simpan.setForeground(Color.white);
    }//GEN-LAST:event_btn_submitMouseEntered

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        // TODO add your handling code here:
        btn_exit.setBackground(new Color(85,65,118));
        tx_exit.setForeground(Color.white);
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
        // TODO add your handling code here:
        btn_exit.setBackground(new Color(255,255,255));
        tx_exit.setForeground(Color.black);
    }//GEN-LAST:event_btn_exitMouseExited

    private void btn_submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseExited
        // TODO add your handling code here:
        btn_submit.setBackground(new Color(255,255,255));
        tx_simpan.setForeground(Color.black);
    }//GEN-LAST:event_btn_submitMouseExited

    private void btn_submit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submit2MouseEntered
        // TODO add your handling code here:
        btn_submit2.setBackground(new Color(126,79,196));
        tx_perbarui.setForeground(Color.white);
    }//GEN-LAST:event_btn_submit2MouseEntered

    private void btn_submit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submit2MouseExited
        // TODO add your handling code here:
        btn_submit2.setBackground(new Color(255,255,255));
        tx_perbarui.setForeground(Color.black);
    }//GEN-LAST:event_btn_submit2MouseExited

    private void btn_viewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewMouseEntered
        // TODO add your handling code here:
        btn_view.setBackground(new Color(126,79,196));
        tx_lihat.setForeground(Color.white);
    }//GEN-LAST:event_btn_viewMouseEntered

    private void btn_viewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_viewMouseExited
        // TODO add your handling code here:
        btn_view.setBackground(new Color(255,255,255));
        tx_lihat.setForeground(Color.black);
    }//GEN-LAST:event_btn_viewMouseExited

    private void btn_dltMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dltMouseEntered
        // TODO add your handling code here:
        btn_dlt.setBackground(new Color(126,79,196));
        tx_hapus.setForeground(Color.white);
    }//GEN-LAST:event_btn_dltMouseEntered

    private void btn_dltMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dltMouseExited
        // TODO add your handling code here:
        btn_dlt.setBackground(new Color(255,255,255));
        tx_hapus.setForeground(Color.black);
    }//GEN-LAST:event_btn_dltMouseExited

    private void tbdataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbdataKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbdataKeyReleased

    private void tx_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_cariKeyReleased
        // TODO add your handling code here:
        String key= tx_cari.getText();
        System.out.println(key);  
        
        if(!"".equals(key)){
            cariData(key);
        }else{
            TampilData();
        }
    }//GEN-LAST:event_tx_cariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project1().setVisible(true);
                
            }
             
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_awal;
    private javax.swing.JComboBox<String> box_jenis;
    private javax.swing.JPanel btn_dlt;
    private javax.swing.JPanel btn_exit;
    private javax.swing.JPanel btn_panALL;
    private javax.swing.JPanel btn_panAbout;
    private javax.swing.JPanel btn_panForm;
    private javax.swing.JPanel btn_submit;
    private javax.swing.JPanel btn_submit2;
    private javax.swing.JPanel btn_view;
    private javax.swing.JLabel ic_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.ButtonGroup jb;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel label_user;
    private javax.swing.JLabel lbl_border;
    private javax.swing.JPanel panel_about;
    private keeptoo.KGradientPanel panel_border;
    private javax.swing.JPanel panel_input;
    private javax.swing.JPanel panel_show;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JRadioButton rb_in;
    private javax.swing.JRadioButton rb_out;
    private javax.swing.JTable tbdata;
    private javax.swing.JTextField tx_cari;
    private javax.swing.JLabel tx_exit;
    private javax.swing.JLabel tx_hapus;
    private javax.swing.JLabel tx_lihat;
    private javax.swing.JLabel tx_perbarui;
    private javax.swing.JLabel tx_simpan;
    private javax.swing.JTextField txt_jml;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextArea txt_note;
    // End of variables declaration//GEN-END:variables
}
